#include<iostream.h>
//#include<stdio.h>
#include<conio.h>

void main()
{
	int no1,no2;
	clrscr();
      /*	printf("Enter no: ");
	scanf("%d",&no);
	printf("Welcome to c. %d\n",no);*/
	cout<<"Enter no1:- ";
	cin>>no1;
	cout<<"Enter no2:- ";
	cin>>no2;
	int no3;
	no3=no1+no2;
	cout<<"Welcome to c++ ";
	cout<<"\nThe sum of "<<no1<<" and "<<no2<<" is "<<no3;
	getch();
//	return 0;
}